on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: paascrdev.azurecr.io
        username: ${{ secrets.acr_paascrdev_username }}
        password: ${{ secrets.acr_paascrdev_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t paascrdev.azurecr.io/aksdev:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push paascrdev.azurecr.io/aksdev:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_aksdev_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep aks-dev8529 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace aks-dev8529`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: aks-dev8529
        container-registry-url: paascrdev.azurecr.io
        container-registry-username: ${{ secrets.acr_paascrdev_username }}
        container-registry-password: ${{ secrets.acr_paascrdev_password }}
        secret-name: aksdevdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: aks-dev8529
        manifests: |
          manifests/deployment-1.yml
          manifests/service-1.yml
          manifests/ingress-1.yml
        images: |
          paascrdev.azurecr.io/aksdev:${{ github.sha }}
        imagepullsecrets: |
          aksdevdockerauth
